
import { VerticalBox, LineEdit, Button } from "std-widgets.slint";
export component AddPlaylist inherits Dialog {
    in-out property <string> playlist-url: "";
    in-out property <string> playlist-name: "";

    callback add_playlist(string, string);

    visible: false;

    Rectangle {
        border-radius: 16px;
        background: #1e1e1e;
        border-width: 1px;
        border-color: #333;
        opacity: 1;

        // ombre simulée
        drop-shadow-blur: 24px;
        drop-shadow-color: #00000088;

        VerticalBox {
            spacing: 20px;
            padding: 20px;

            LineEdit {
                placeholder-text: "playlist name";
                input-type: InputType.text;
                height: 40px;
                horizontal-stretch: 1;

                edited(value) => {
                    root.playlist-name = value;
                }
            }

            LineEdit {
                placeholder-text: "playlist url";
                input-type: InputType.text;
                height: 40px;
                horizontal-stretch: 1;

                edited(value) => {
                    root.playlist-url = value;
                }
            }

            Button {
                text: "add";
                width: 120px;
                height: 40px;

                clicked => {
                    root.add_playlist(root.playlist-name, root.playlist-url);
                    root.visible = false;
                }
            }
        }
    }
}
