
import {
    VerticalBox,
    LineEdit,
    Button,
    HorizontalBox,
} from "std-widgets.slint";
export component AddPlaylist inherits Dialog {
    in-out property <string> playlist-url: "";
    in-out property <string> playlist-name: "";

    callback add_playlist(string, string);

    visible: false;

    Rectangle {
        border-radius: 16px;
        background: #1e1e1e;
        border-width: 1px;
        border-color: #333;
        opacity: 1;

        // ombre simulée
        drop-shadow-blur: 24px;
        drop-shadow-color: #00000088;

        VerticalBox {
            spacing: 20px;
            padding: 20px;

            VerticalBox {
                LineEdit {
                    placeholder-text: "playlist name";
                    input-type: InputType.text;
                    height: 40px;
                    horizontal-stretch: 1;
    
                    edited(value) => {
                        root.playlist-name = value;
                    }
                }

                playlist-name-error := Text {
                    accessible-id: "playlist-name-error";
                    text: "Please enter a playlist name.";
                    color: red;
                    visible: false; 
                }
            }


            VerticalBox {
                LineEdit {
                    placeholder-text: "playlist url";
                    input-type: InputType.text;
                    height: 40px;
                    horizontal-stretch: 1;
    
                    edited(value) => {
                        root.playlist-url = value;
                    }
                }

                playlist-url-error := Text {
                    accessible-id: "playlist-url-error";
                    text: "Please enter a valid URL.";
                    color: red;
                    visible: false; 
                }
            }

            HorizontalBox {
                Button {
                    text: "add";
                    width: 120px;
                    height: 40px;
                    clicked => {
                        if (root.playlist-name != "" && root.playlist-url != "") {
                            root.add_playlist(root.playlist-name, root.playlist-url);
                            root.visible = false;
                        } else {
                            playlist-url-error.visible = root.playlist-url == "";
                            playlist-name-error.visible = root.playlist-name == "";

                        }
                    }
                }

                Button {
                    text: "cancel";
                    width: 120px;
                    height: 40px;
                    clicked => {
                        root.visible = false;
                    }
                }
            }
        }
    }
}
