import { HorizontalBox } from "std-widgets.slint";

export component PlaylistItem inherits Rectangle {
    in property <string> title;
    in property <string> id;
    callback manage_playlist_display(string);
    callback refresh_playlist(string);
    callback delete_playlist(string);

    height: 50px;
    border-width: 2px;
    border-color: #444;
    border-radius: 12px;

    TouchArea {
        width: parent.width;
        height: parent.height;
    }

    HorizontalLayout {
        height: 50px;
        padding-left: 12px;

        Text {
            width: 60%;
            height: 100%;
            text: title;
            vertical-alignment: center;
            horizontal-alignment: left;
            overflow: elide;
        }

        HorizontalBox {
            width: 40%;
            height: 50px;
            spacing: 10px;

            Rectangle {
                border-radius: 40px;
                border-color: refresh.has-hover ? blue : white;
                border-width: 1px;
                width: 32px;
                height: 32px;

                animate border-color { duration: 150ms; }

                Image {
                    height: 20px;
                    width: 20px;
                    source: @image-url("../assets/icon-refresh.svg");
                    colorize: refresh.has-hover ? blue : white;

                    animate colorize { duration: 150ms; }
                }

                refresh := TouchArea {
                    width: 100%;
                    height: 100%;
                    mouse-cursor: pointer;
                    clicked => {
                        root.refresh_playlist(id);
                    }
                }
            }

            Rectangle {
                border-radius: 40px;
                border-color: delete.has-hover ? red : white;
                border-width: 1px;
                width: 32px;
                height: 32px;

                animate border-color { duration: 150ms; }

                Image {
                    height: 20px;
                    width: 20px;
                    source: @image-url("../assets/icon-bin.svg");
                    colorize: delete.has-hover ? red : white;

                    animate colorize { duration: 150ms; }
                }

                delete := TouchArea {
                    width: 100%;
                    height: 100%;
                    mouse-cursor: pointer;
                    clicked => {
                        root.delete_playlist(id);
                    }
                }
            }
        }
    }
}