import { VerticalBox, Button, ScrollView } from "std-widgets.slint";
import { PlaylistItem } from "playlist-item.slint";
import { Playlist } from "../structs/playlist.slint";
import { AppLogic } from "../globals/callbacks.slint";
import { DialogType } from "../enums/dialog-type.slint";
import { AddPlaylist } from "../dialog/add-playlist.slint";
import { SettingDialog } from "../dialog/settings.slint";

export component Sidebar inherits Rectangle {
    in property <[Playlist]> playlists;
    in property <string> name;
    callback open_dialog(DialogType);

    width: 300px;
    border-width: 2px;
    border-color: #444;
    border-radius: 20px;

    VerticalBox {
        padding: 16px;
        spacing: 16px;

        Text {
            text: "tracked playlists";
            font-size: 18px;
        }

        Button {
            text: "add playlist";
            height: 40px;
            icon: @image-url("../assets/icon-plus.svg");
            icon-size: 16px;

            clicked => {
                open_dialog(DialogType.CreatePlaylist)
            }
        }

        ScrollView {

            VerticalBox {
                spacing: 8px;

                for pl in playlists : PlaylistItem {
                    playlist: pl;
                }
            }
        }

        Button {
            text: "settings";
            height: 40px;

            clicked => {
                open_dialog(DialogType.Settings)
            }
        }
    }
}