import { HorizontalBox } from "std-widgets.slint";
import { CircularProgressIndicator } from "../../material/index.slint";

export struct Song {
    title: string,
    is_downloading: bool,
}

export component SongItem inherits Rectangle {
    in property <string> title;
    in property <bool> is_downloading: false;
    callback download_clicked;

    height: 90px;
    border-width: 2px;
    border-color: #444;
    border-radius: 20px;

    HorizontalBox {
        spacing: 20px;
        padding: 15px;

        // Image placeholder
        Rectangle {
            width: 60px;
            height: 60px;
            border-width: 2px;
            border-color: #444;
            border-radius: 12px;

            Text {
                text: "image";
                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }

        // Song title
        Text {
            text: title;
            vertical-alignment: center;
            font-size: 18px;
            horizontal-stretch: 1;
        }

        // Download indicator button
        Rectangle {
            width: 40px;
            height: 40px;
            border-radius: 20px;

            CircularProgressIndicator {
                indeterminate: root.is_downloading;
                visible: root.is_downloading;
            }

            TouchArea {
                clicked => {
                    root.download_clicked();
                }
            }
        }
    }
}
